# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ac047a4315a3b1c189dc81b3d029964a3baf6ed8582310e829d1452e7a40e5e000a47b20249aa6da1c34b6c6a8dcbbea71e547e95550eba51c6616fd08001cc

test:
  secret_key_base: 1c12bf45d677db509a07b25772b6d3c5caa99139e05975d3de0ddbc4e95c0c4639d8d05be9727c2efe63d5c75e8875a0ef66fc641ba109f9e494592a054ff048

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
